FROM golang:alpine3.19 AS builder

WORKDIR /usr/src/app

COPY ./app .

RUN go build -ldflags '-s -w' -o fullcycle

RUN apk update && apk add --no-cache upx && \
    upx --best --lzma fullcycle

FROM scratch

WORKDIR /usr/src/app

COPY --from=builder ./usr/src/app .

CMD ["./fullcycle"]