FROM golang:alpine3.19 AS builder

WORKDIR /usr/src/app

COPY ./app .

RUN mkdir ../target

RUN go build -ldflags '-s -w' -o ../target/fullcycle

RUN apk update && apk add --no-cache upx && \
    upx --best --lzma ../target/fullcycle

FROM scratch

WORKDIR /usr/src/target

COPY --from=builder ./usr/src/target .

CMD ["./fullcycle"]